package csv

import (
	"strings"
	"testing"

	"github.com/darianmavgo/mksqlite/converters/common"
)

func TestAdvancedHeaderDetection(t *testing.T) {
	csvContent := `Metadata: info
Generated by: Tool
Date: 2023-01-01

Name,Age,Role
Alice,30,Engineer
Bob,25,Designer
`
	reader := strings.NewReader(csvContent)
	config := &common.ConversionConfig{
		AdvancedHeaderDetection: true,
	}

	converter, err := NewCSVConverterWithConfig(reader, config)
	if err != nil {
		t.Fatalf("Failed to create converter: %v", err)
	}

	headers := converter.GetHeaders(CSVTB)
	expectedHeaders := []string{"name", "age", "role"}

	// Check headers
	if len(headers) != len(expectedHeaders) {
		t.Fatalf("Expected %d headers, got %d: %v", len(expectedHeaders), len(headers), headers)
	}

	for i, h := range headers {
		if h != expectedHeaders[i] {
			t.Errorf("Header %d: expected %s, got %s", i, expectedHeaders[i], h)
		}
	}

	// Check rows
	var rows [][]interface{}
	err = converter.ScanRows(CSVTB, func(row []interface{}) error {
		rows = append(rows, row)
		return nil
	})
	if err != nil {
		t.Fatalf("ScanRows failed: %v", err)
	}

	if len(rows) != 2 {
		t.Errorf("Expected 2 data rows, got %d", len(rows))
	}

	if len(rows) > 0 {
		firstRow := rows[0]
		if firstRow[0] != "Alice" {
			t.Errorf("First row name: expected Alice, got %v", firstRow[0])
		}
	}
}

func TestDefaultHeaderDetection(t *testing.T) {
	csvContent := `Metadata: info
Generated by: Tool

Name,Age,Role
Alice,30,Engineer
`
	reader := strings.NewReader(csvContent)
	// Default config (false)
	config := &common.ConversionConfig{
		AdvancedHeaderDetection: false,
	}

	converter, err := NewCSVConverterWithConfig(reader, config)
	if err != nil {
		t.Fatalf("Failed to create converter: %v", err)
	}

	headers := converter.GetHeaders(CSVTB)
	// Expecting "metadata_info" or similar sanitized version of first row
	if len(headers) == 0 || !strings.Contains(headers[0], "metadata") {
		t.Errorf("Expected default behavior (first row as header), got headers: %v", headers)
	}
}
