CREATE TABLE organized (line_num TEXT, heading TEXT, role TEXT, location TEXT, organization TEXT, start_date TEXT, end_date TEXT, description TEXT);

INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Education', 'Undergraduate Studies', 'Johns Hopkins University', '-', '1997/09', '2001/05', 'B.S. in Computer Science');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Software Engineer', '-', 'ITT Industries Advanced Engineering and Sciences', '2002/01', '2003/09', 'Trained team in Java, Perl, and Linux Server Administration.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Software Engineer', '-', 'Object Sciences Corporation', '2003/09', '2004/06', 'Evaluated and deployed messaging platforms and software demonstrations.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Software Engineer', '-', 'Technology Management Associates', '2004/06', '2005/04', 'Java apps and data transformation projects.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Founder', 'Various', 'Village the Game', '2006/05', 'Present', 'Tech development, managing team, and networking.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Sustainable Development Lecturer', 'Thailand', 'Chiang Mai University', '2008/01', '2008/12', 'Lecture on Sustainable Development.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Programmer Project Manager', '-', 'Numedeon Inc.', '2008/05', '2008/11', 'Led development teams and managed online ad campaigns.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Data Management Instructor', '-', 'Talend Inc.', '2009/02', 'Present', 'Teaching data management courses.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Sales and Support Engineer', '-', 'Talend Inc.', '2009/02', '2011/03', 'Developed demonstrations and provided training for Talend software.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'GMAT Prep Instructor', '-', 'RevolutionPrep', '2010/01', '2010/12', 'GMAT Prep Instruction.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Guest Lecturer', 'Southern California', 'University of Southern California', '2010/03', '2010/03', 'Lecture on Social Cause Games.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Talend Consultant', '-', 'Independent', '2011/03', 'Present', 'Taught online class and advised on health care data fraud detection.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Talend Consultant', '-', 'Mavgo', '2011/08', 'Present', 'Data migration and Talend job development.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Talend Consultant', '-', 'Google', '2012/10', '2014/10', 'Led team for Talend Administration Center installations.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Guest Lecturer', 'Tanzania', 'United African University of Tanzania', '2013/07', '2013/07', 'Lecture on Entrepreneurship and Value Creation.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Volunteer', 'Volunteer', 'Tanzania', 'United African University of Tanzania', '2013/07', '2013/07', 'Business intensive on Entrepreneurship and Value Creation.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Solution Architect', '-', 'Luuruu', '2014/02', '2014/08', 'Technology stack for scaling a translation company.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Work', 'Talend Architect Consultant', '-', 'Home Depot and TCS', '2014/09', '2015/03', 'Talend workflow design and Salesforce integration.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Volunteer', 'Volunteer', '-', 'Seeds of Hope', '-', '-', 'Upgraded IT systems and taught business units.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Volunteer', 'Volunteer', 'Nicaragua', 'Blue Energy Group', '-', '-', 'Installed biosand filters and solar panels.');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Publication', '', '', '', '', '', '');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Award', '', '', '', '', '', '');
INSERT INTO organized (line_num, heading, role, location, organization, start_date, end_date, description) VALUES ('', 'Contact Info', '', '', 'American Comedy Institute', '2015/01', '', 'Stand Up
Stephen Rosenfield

');

CREATE TABLE timeline (start_date TEXT);

INSERT INTO timeline (start_date) VALUES ('2024/01');
INSERT INTO timeline (start_date) VALUES ('2023/12');
INSERT INTO timeline (start_date) VALUES ('2023/11');
INSERT INTO timeline (start_date) VALUES ('2023/10');
INSERT INTO timeline (start_date) VALUES ('2023/09');
INSERT INTO timeline (start_date) VALUES ('2023/8');
INSERT INTO timeline (start_date) VALUES ('2023/07');
INSERT INTO timeline (start_date) VALUES ('2023/6');
INSERT INTO timeline (start_date) VALUES ('2023/05');
INSERT INTO timeline (start_date) VALUES ('2023/4');
INSERT INTO timeline (start_date) VALUES ('2023/03');
INSERT INTO timeline (start_date) VALUES ('2023/2');
INSERT INTO timeline (start_date) VALUES ('2023/01');
INSERT INTO timeline (start_date) VALUES ('2022/12');
INSERT INTO timeline (start_date) VALUES ('2022/11');
INSERT INTO timeline (start_date) VALUES ('2022/10');
INSERT INTO timeline (start_date) VALUES ('2022/09');
INSERT INTO timeline (start_date) VALUES ('2022/8');
INSERT INTO timeline (start_date) VALUES ('2022/07');
INSERT INTO timeline (start_date) VALUES ('2022/6');
INSERT INTO timeline (start_date) VALUES ('2022/05');
INSERT INTO timeline (start_date) VALUES ('2022/4');
INSERT INTO timeline (start_date) VALUES ('2022/03');
INSERT INTO timeline (start_date) VALUES ('2022/2');
INSERT INTO timeline (start_date) VALUES ('2022/01');
INSERT INTO timeline (start_date) VALUES ('2021/12');
INSERT INTO timeline (start_date) VALUES ('2021/11');
INSERT INTO timeline (start_date) VALUES ('2021/10');
INSERT INTO timeline (start_date) VALUES ('2021/09');
INSERT INTO timeline (start_date) VALUES ('2021/8');
INSERT INTO timeline (start_date) VALUES ('2021/07');
INSERT INTO timeline (start_date) VALUES ('2021/6');
INSERT INTO timeline (start_date) VALUES ('2021/05');
INSERT INTO timeline (start_date) VALUES ('2021/4');
INSERT INTO timeline (start_date) VALUES ('2021/03');
INSERT INTO timeline (start_date) VALUES ('2021/2');
INSERT INTO timeline (start_date) VALUES ('2021/01');
INSERT INTO timeline (start_date) VALUES ('2020/12');
INSERT INTO timeline (start_date) VALUES ('2020/11');
INSERT INTO timeline (start_date) VALUES ('2020/10');
INSERT INTO timeline (start_date) VALUES ('2020/09');
INSERT INTO timeline (start_date) VALUES ('2020/8');
INSERT INTO timeline (start_date) VALUES ('2020/07');
INSERT INTO timeline (start_date) VALUES ('2020/6');
INSERT INTO timeline (start_date) VALUES ('2020/05');
INSERT INTO timeline (start_date) VALUES ('2020/4');
INSERT INTO timeline (start_date) VALUES ('2020/03');
INSERT INTO timeline (start_date) VALUES ('2020/2');
INSERT INTO timeline (start_date) VALUES ('2020/01');
INSERT INTO timeline (start_date) VALUES ('2019/12');
INSERT INTO timeline (start_date) VALUES ('2019/11');
INSERT INTO timeline (start_date) VALUES ('2019/10');
INSERT INTO timeline (start_date) VALUES ('2019/09');
INSERT INTO timeline (start_date) VALUES ('2019/8');
INSERT INTO timeline (start_date) VALUES ('2019/07');
INSERT INTO timeline (start_date) VALUES ('2019/6');
INSERT INTO timeline (start_date) VALUES ('2019/05');
INSERT INTO timeline (start_date) VALUES ('2019/4');
INSERT INTO timeline (start_date) VALUES ('2019/03');
INSERT INTO timeline (start_date) VALUES ('2019/2');
INSERT INTO timeline (start_date) VALUES ('2019/01');
INSERT INTO timeline (start_date) VALUES ('2018/12');
INSERT INTO timeline (start_date) VALUES ('2018/11');
INSERT INTO timeline (start_date) VALUES ('2018/10');
INSERT INTO timeline (start_date) VALUES ('2018/09');
INSERT INTO timeline (start_date) VALUES ('2018/8');
INSERT INTO timeline (start_date) VALUES ('2018/07');
INSERT INTO timeline (start_date) VALUES ('2018/6');
INSERT INTO timeline (start_date) VALUES ('2018/05');
INSERT INTO timeline (start_date) VALUES ('2018/4');
INSERT INTO timeline (start_date) VALUES ('2018/03');
INSERT INTO timeline (start_date) VALUES ('2018/2');
INSERT INTO timeline (start_date) VALUES ('2018/01');
INSERT INTO timeline (start_date) VALUES ('2017/12');
INSERT INTO timeline (start_date) VALUES ('2017/11');
INSERT INTO timeline (start_date) VALUES ('2017/10');
INSERT INTO timeline (start_date) VALUES ('2017/09');
INSERT INTO timeline (start_date) VALUES ('2017/8');
INSERT INTO timeline (start_date) VALUES ('2017/07');
INSERT INTO timeline (start_date) VALUES ('2017/6');
INSERT INTO timeline (start_date) VALUES ('2017/05');
INSERT INTO timeline (start_date) VALUES ('2017/4');
INSERT INTO timeline (start_date) VALUES ('2017/03');
INSERT INTO timeline (start_date) VALUES ('2017/2');
INSERT INTO timeline (start_date) VALUES ('2017/01');
INSERT INTO timeline (start_date) VALUES ('2016/12');
INSERT INTO timeline (start_date) VALUES ('2016/11');
INSERT INTO timeline (start_date) VALUES ('2016/10');
INSERT INTO timeline (start_date) VALUES ('2016/09');
INSERT INTO timeline (start_date) VALUES ('2016/8');
INSERT INTO timeline (start_date) VALUES ('2016/07');
INSERT INTO timeline (start_date) VALUES ('2016/6');
INSERT INTO timeline (start_date) VALUES ('2016/05');
INSERT INTO timeline (start_date) VALUES ('2016/4');
INSERT INTO timeline (start_date) VALUES ('2016/03');
INSERT INTO timeline (start_date) VALUES ('2016/2');
INSERT INTO timeline (start_date) VALUES ('2016/01');
INSERT INTO timeline (start_date) VALUES ('2015/12');
INSERT INTO timeline (start_date) VALUES ('2015/11');
INSERT INTO timeline (start_date) VALUES ('2015/10');
INSERT INTO timeline (start_date) VALUES ('2015/09');
INSERT INTO timeline (start_date) VALUES ('2015/8');
INSERT INTO timeline (start_date) VALUES ('2015/07');
INSERT INTO timeline (start_date) VALUES ('2015/6');
INSERT INTO timeline (start_date) VALUES ('2015/05');
INSERT INTO timeline (start_date) VALUES ('2015/4');
INSERT INTO timeline (start_date) VALUES ('2015/03');
INSERT INTO timeline (start_date) VALUES ('2015/2');
INSERT INTO timeline (start_date) VALUES ('2015/01');
INSERT INTO timeline (start_date) VALUES ('2014/12');
INSERT INTO timeline (start_date) VALUES ('2014/11');
INSERT INTO timeline (start_date) VALUES ('2014/10');
INSERT INTO timeline (start_date) VALUES ('2014/09');
INSERT INTO timeline (start_date) VALUES ('2014/8');
INSERT INTO timeline (start_date) VALUES ('2014/07');
INSERT INTO timeline (start_date) VALUES ('2014/6');
INSERT INTO timeline (start_date) VALUES ('2014/05');
INSERT INTO timeline (start_date) VALUES ('2014/4');
INSERT INTO timeline (start_date) VALUES ('2014/03');
INSERT INTO timeline (start_date) VALUES ('2014/2');
INSERT INTO timeline (start_date) VALUES ('2014/01');
INSERT INTO timeline (start_date) VALUES ('2013/12');
INSERT INTO timeline (start_date) VALUES ('2013/11');
INSERT INTO timeline (start_date) VALUES ('2013/10');
INSERT INTO timeline (start_date) VALUES ('2013/09');
INSERT INTO timeline (start_date) VALUES ('2013/8');
INSERT INTO timeline (start_date) VALUES ('2013/07');
INSERT INTO timeline (start_date) VALUES ('2013/6');
INSERT INTO timeline (start_date) VALUES ('2013/05');
INSERT INTO timeline (start_date) VALUES ('2013/4');
INSERT INTO timeline (start_date) VALUES ('2013/03');
INSERT INTO timeline (start_date) VALUES ('2013/2');
INSERT INTO timeline (start_date) VALUES ('2013/01');
INSERT INTO timeline (start_date) VALUES ('2012/12');
INSERT INTO timeline (start_date) VALUES ('2012/11');
INSERT INTO timeline (start_date) VALUES ('2012/10');
INSERT INTO timeline (start_date) VALUES ('2012/09');
INSERT INTO timeline (start_date) VALUES ('2012/8');
INSERT INTO timeline (start_date) VALUES ('2012/07');
INSERT INTO timeline (start_date) VALUES ('2012/6');
INSERT INTO timeline (start_date) VALUES ('2012/05');
INSERT INTO timeline (start_date) VALUES ('2012/4');
INSERT INTO timeline (start_date) VALUES ('2012/03');
INSERT INTO timeline (start_date) VALUES ('2012/2');
INSERT INTO timeline (start_date) VALUES ('2012/01');
INSERT INTO timeline (start_date) VALUES ('2011/12');
INSERT INTO timeline (start_date) VALUES ('2011/11');
INSERT INTO timeline (start_date) VALUES ('2011/10');
INSERT INTO timeline (start_date) VALUES ('2011/09');
INSERT INTO timeline (start_date) VALUES ('2011/8');
INSERT INTO timeline (start_date) VALUES ('2011/07');
INSERT INTO timeline (start_date) VALUES ('2011/6');
INSERT INTO timeline (start_date) VALUES ('2011/05');
INSERT INTO timeline (start_date) VALUES ('2011/4');
INSERT INTO timeline (start_date) VALUES ('2011/03');
INSERT INTO timeline (start_date) VALUES ('2011/2');
INSERT INTO timeline (start_date) VALUES ('2011/01');
INSERT INTO timeline (start_date) VALUES ('2010/12');
INSERT INTO timeline (start_date) VALUES ('2010/11');
INSERT INTO timeline (start_date) VALUES ('2010/10');
INSERT INTO timeline (start_date) VALUES ('2010/09');
INSERT INTO timeline (start_date) VALUES ('2010/8');
INSERT INTO timeline (start_date) VALUES ('2010/07');
INSERT INTO timeline (start_date) VALUES ('2010/6');
INSERT INTO timeline (start_date) VALUES ('2010/05');
INSERT INTO timeline (start_date) VALUES ('2010/4');
INSERT INTO timeline (start_date) VALUES ('2010/03');
INSERT INTO timeline (start_date) VALUES ('2010/2');
INSERT INTO timeline (start_date) VALUES ('2010/01');
INSERT INTO timeline (start_date) VALUES ('2009/12');
INSERT INTO timeline (start_date) VALUES ('2009/11');
INSERT INTO timeline (start_date) VALUES ('2009/10');
INSERT INTO timeline (start_date) VALUES ('2009/09');
INSERT INTO timeline (start_date) VALUES ('2009/8');
INSERT INTO timeline (start_date) VALUES ('2009/07');
INSERT INTO timeline (start_date) VALUES ('2009/6');
INSERT INTO timeline (start_date) VALUES ('2009/05');
INSERT INTO timeline (start_date) VALUES ('2009/4');
INSERT INTO timeline (start_date) VALUES ('2009/03');
INSERT INTO timeline (start_date) VALUES ('2009/2');
INSERT INTO timeline (start_date) VALUES ('2009/01');
INSERT INTO timeline (start_date) VALUES ('2008/12');
INSERT INTO timeline (start_date) VALUES ('2008/11');
INSERT INTO timeline (start_date) VALUES ('2008/10');
INSERT INTO timeline (start_date) VALUES ('2008/09');
INSERT INTO timeline (start_date) VALUES ('2008/8');
INSERT INTO timeline (start_date) VALUES ('2008/07');
INSERT INTO timeline (start_date) VALUES ('2008/6');
INSERT INTO timeline (start_date) VALUES ('2008/05');
INSERT INTO timeline (start_date) VALUES ('2008/4');
INSERT INTO timeline (start_date) VALUES ('2008/03');
INSERT INTO timeline (start_date) VALUES ('2008/2');
INSERT INTO timeline (start_date) VALUES ('2008/01');
INSERT INTO timeline (start_date) VALUES ('2007/12');
INSERT INTO timeline (start_date) VALUES ('2007/11');
INSERT INTO timeline (start_date) VALUES ('2007/10');
INSERT INTO timeline (start_date) VALUES ('2007/09');
INSERT INTO timeline (start_date) VALUES ('2007/8');
INSERT INTO timeline (start_date) VALUES ('2007/07');
INSERT INTO timeline (start_date) VALUES ('2007/6');
INSERT INTO timeline (start_date) VALUES ('2007/05');
INSERT INTO timeline (start_date) VALUES ('2007/4');
INSERT INTO timeline (start_date) VALUES ('2007/03');
INSERT INTO timeline (start_date) VALUES ('2007/2');
INSERT INTO timeline (start_date) VALUES ('2007/01');
INSERT INTO timeline (start_date) VALUES ('2006/12');
INSERT INTO timeline (start_date) VALUES ('2006/11');
INSERT INTO timeline (start_date) VALUES ('2006/10');
INSERT INTO timeline (start_date) VALUES ('2006/09');
INSERT INTO timeline (start_date) VALUES ('2006/8');
INSERT INTO timeline (start_date) VALUES ('2006/07');
INSERT INTO timeline (start_date) VALUES ('2006/6');
INSERT INTO timeline (start_date) VALUES ('2006/05');
INSERT INTO timeline (start_date) VALUES ('2006/4');
INSERT INTO timeline (start_date) VALUES ('2006/03');
INSERT INTO timeline (start_date) VALUES ('2006/2');
INSERT INTO timeline (start_date) VALUES ('2006/01');
INSERT INTO timeline (start_date) VALUES ('2005/12');
INSERT INTO timeline (start_date) VALUES ('2005/11');
INSERT INTO timeline (start_date) VALUES ('2005/10');
INSERT INTO timeline (start_date) VALUES ('2005/09');
INSERT INTO timeline (start_date) VALUES ('2005/8');
INSERT INTO timeline (start_date) VALUES ('2005/07');
INSERT INTO timeline (start_date) VALUES ('2005/6');
INSERT INTO timeline (start_date) VALUES ('2005/05');
INSERT INTO timeline (start_date) VALUES ('2005/4');
INSERT INTO timeline (start_date) VALUES ('2005/03');
INSERT INTO timeline (start_date) VALUES ('2005/2');
INSERT INTO timeline (start_date) VALUES ('2005/01');
INSERT INTO timeline (start_date) VALUES ('2004/12');
INSERT INTO timeline (start_date) VALUES ('2004/11');
INSERT INTO timeline (start_date) VALUES ('2004/10');
INSERT INTO timeline (start_date) VALUES ('2004/09');
INSERT INTO timeline (start_date) VALUES ('2004/8');
INSERT INTO timeline (start_date) VALUES ('2004/07');
INSERT INTO timeline (start_date) VALUES ('2004/6');
INSERT INTO timeline (start_date) VALUES ('2004/05');
INSERT INTO timeline (start_date) VALUES ('2004/4');
INSERT INTO timeline (start_date) VALUES ('2004/03');
INSERT INTO timeline (start_date) VALUES ('2004/2');
INSERT INTO timeline (start_date) VALUES ('2004/01');
INSERT INTO timeline (start_date) VALUES ('2003/12');
INSERT INTO timeline (start_date) VALUES ('2003/11');
INSERT INTO timeline (start_date) VALUES ('2003/10');
INSERT INTO timeline (start_date) VALUES ('2003/09');
INSERT INTO timeline (start_date) VALUES ('2003/8');
INSERT INTO timeline (start_date) VALUES ('2003/07');
INSERT INTO timeline (start_date) VALUES ('2003/6');
INSERT INTO timeline (start_date) VALUES ('2003/05');
INSERT INTO timeline (start_date) VALUES ('2003/4');
INSERT INTO timeline (start_date) VALUES ('2003/03');
INSERT INTO timeline (start_date) VALUES ('2003/2');
INSERT INTO timeline (start_date) VALUES ('2003/01');
INSERT INTO timeline (start_date) VALUES ('2002/12');
INSERT INTO timeline (start_date) VALUES ('2002/11');
INSERT INTO timeline (start_date) VALUES ('2002/10');
INSERT INTO timeline (start_date) VALUES ('2002/09');
INSERT INTO timeline (start_date) VALUES ('2002/8');
INSERT INTO timeline (start_date) VALUES ('2002/07');
INSERT INTO timeline (start_date) VALUES ('2002/6');
INSERT INTO timeline (start_date) VALUES ('2002/05');
INSERT INTO timeline (start_date) VALUES ('2002/4');
INSERT INTO timeline (start_date) VALUES ('2002/03');
INSERT INTO timeline (start_date) VALUES ('2002/2');
INSERT INTO timeline (start_date) VALUES ('2002/01');
INSERT INTO timeline (start_date) VALUES ('2001/12');
INSERT INTO timeline (start_date) VALUES ('2001/11');
INSERT INTO timeline (start_date) VALUES ('2001/10');
INSERT INTO timeline (start_date) VALUES ('2001/09');
INSERT INTO timeline (start_date) VALUES ('2001/8');
INSERT INTO timeline (start_date) VALUES ('2001/07');
INSERT INTO timeline (start_date) VALUES ('2001/6');
INSERT INTO timeline (start_date) VALUES ('2001/05');
INSERT INTO timeline (start_date) VALUES ('2001/4');
INSERT INTO timeline (start_date) VALUES ('2001/03');
INSERT INTO timeline (start_date) VALUES ('2001/2');
INSERT INTO timeline (start_date) VALUES ('2001/01');
INSERT INTO timeline (start_date) VALUES ('2000/12');
INSERT INTO timeline (start_date) VALUES ('2000/11');
INSERT INTO timeline (start_date) VALUES ('2000/10');
INSERT INTO timeline (start_date) VALUES ('2000/09');
INSERT INTO timeline (start_date) VALUES ('2000/8');
INSERT INTO timeline (start_date) VALUES ('2000/07');
INSERT INTO timeline (start_date) VALUES ('2000/6');
INSERT INTO timeline (start_date) VALUES ('2000/05');
INSERT INTO timeline (start_date) VALUES ('2000/4');
INSERT INTO timeline (start_date) VALUES ('2000/03');
INSERT INTO timeline (start_date) VALUES ('2000/2');
INSERT INTO timeline (start_date) VALUES ('2000/01');
INSERT INTO timeline (start_date) VALUES ('1999/12');
INSERT INTO timeline (start_date) VALUES ('1999/11');
INSERT INTO timeline (start_date) VALUES ('1999/10');
INSERT INTO timeline (start_date) VALUES ('1999/09');
INSERT INTO timeline (start_date) VALUES ('1999/8');
INSERT INTO timeline (start_date) VALUES ('1999/07');
INSERT INTO timeline (start_date) VALUES ('1999/6');
INSERT INTO timeline (start_date) VALUES ('1999/05');
INSERT INTO timeline (start_date) VALUES ('1999/4');
INSERT INTO timeline (start_date) VALUES ('1999/03');
INSERT INTO timeline (start_date) VALUES ('1999/2');
INSERT INTO timeline (start_date) VALUES ('1999/01');
INSERT INTO timeline (start_date) VALUES ('1998/12');
INSERT INTO timeline (start_date) VALUES ('1998/11');
INSERT INTO timeline (start_date) VALUES ('1998/10');
INSERT INTO timeline (start_date) VALUES ('1998/09');
INSERT INTO timeline (start_date) VALUES ('1998/8');
INSERT INTO timeline (start_date) VALUES ('1998/07');
INSERT INTO timeline (start_date) VALUES ('1998/6');
INSERT INTO timeline (start_date) VALUES ('1998/05');
INSERT INTO timeline (start_date) VALUES ('1998/4');
INSERT INTO timeline (start_date) VALUES ('1998/03');
INSERT INTO timeline (start_date) VALUES ('1998/2');
INSERT INTO timeline (start_date) VALUES ('1998/01');
INSERT INTO timeline (start_date) VALUES ('1997/12');
INSERT INTO timeline (start_date) VALUES ('1997/11');
INSERT INTO timeline (start_date) VALUES ('1997/10');
INSERT INTO timeline (start_date) VALUES ('1997/09');
INSERT INTO timeline (start_date) VALUES ('1997/8');
INSERT INTO timeline (start_date) VALUES ('1997/07');
INSERT INTO timeline (start_date) VALUES ('1997/6');
INSERT INTO timeline (start_date) VALUES ('1997/05');
INSERT INTO timeline (start_date) VALUES ('1997/4');
INSERT INTO timeline (start_date) VALUES ('1997/03');
INSERT INTO timeline (start_date) VALUES ('1997/2');
INSERT INTO timeline (start_date) VALUES ('1997/01');
INSERT INTO timeline (start_date) VALUES ('1996/12');
INSERT INTO timeline (start_date) VALUES ('1996/11');
INSERT INTO timeline (start_date) VALUES ('1996/10');
INSERT INTO timeline (start_date) VALUES ('1996/09');
INSERT INTO timeline (start_date) VALUES ('1996/8');
INSERT INTO timeline (start_date) VALUES ('1996/07');
INSERT INTO timeline (start_date) VALUES ('1996/6');
INSERT INTO timeline (start_date) VALUES ('1996/05');
INSERT INTO timeline (start_date) VALUES ('1996/4');
INSERT INTO timeline (start_date) VALUES ('1996/03');
INSERT INTO timeline (start_date) VALUES ('1996/2');
INSERT INTO timeline (start_date) VALUES ('1996/01');
INSERT INTO timeline (start_date) VALUES ('1995/12');
INSERT INTO timeline (start_date) VALUES ('1995/11');
INSERT INTO timeline (start_date) VALUES ('1995/10');
INSERT INTO timeline (start_date) VALUES ('1995/09');
INSERT INTO timeline (start_date) VALUES ('1995/8');
INSERT INTO timeline (start_date) VALUES ('1995/07');
INSERT INTO timeline (start_date) VALUES ('1995/6');
INSERT INTO timeline (start_date) VALUES ('1995/05');
INSERT INTO timeline (start_date) VALUES ('1995/4');
INSERT INTO timeline (start_date) VALUES ('1995/03');
INSERT INTO timeline (start_date) VALUES ('1995/2');
INSERT INTO timeline (start_date) VALUES ('1995/01');
INSERT INTO timeline (start_date) VALUES ('1994/12');
INSERT INTO timeline (start_date) VALUES ('1994/11');
INSERT INTO timeline (start_date) VALUES ('1994/10');
INSERT INTO timeline (start_date) VALUES ('1994/09');
INSERT INTO timeline (start_date) VALUES ('1994/8');
INSERT INTO timeline (start_date) VALUES ('1994/07');
INSERT INTO timeline (start_date) VALUES ('1994/6');
INSERT INTO timeline (start_date) VALUES ('1994/05');
INSERT INTO timeline (start_date) VALUES ('1994/4');
INSERT INTO timeline (start_date) VALUES ('1994/03');
INSERT INTO timeline (start_date) VALUES ('1994/2');
INSERT INTO timeline (start_date) VALUES ('1994/01');
INSERT INTO timeline (start_date) VALUES ('1993/12');
INSERT INTO timeline (start_date) VALUES ('1993/11');
INSERT INTO timeline (start_date) VALUES ('1993/10');
INSERT INTO timeline (start_date) VALUES ('1993/09');
INSERT INTO timeline (start_date) VALUES ('1993/8');
INSERT INTO timeline (start_date) VALUES ('1993/07');
INSERT INTO timeline (start_date) VALUES ('1993/6');
INSERT INTO timeline (start_date) VALUES ('1993/05');
INSERT INTO timeline (start_date) VALUES ('1993/4');
INSERT INTO timeline (start_date) VALUES ('1993/03');
INSERT INTO timeline (start_date) VALUES ('1993/2');
INSERT INTO timeline (start_date) VALUES ('1993/01');
INSERT INTO timeline (start_date) VALUES ('1992/12');
INSERT INTO timeline (start_date) VALUES ('1992/11');
INSERT INTO timeline (start_date) VALUES ('1992/10');
INSERT INTO timeline (start_date) VALUES ('1992/09');
INSERT INTO timeline (start_date) VALUES ('1992/8');
INSERT INTO timeline (start_date) VALUES ('1992/07');
INSERT INTO timeline (start_date) VALUES ('1992/6');
INSERT INTO timeline (start_date) VALUES ('1992/05');
INSERT INTO timeline (start_date) VALUES ('1992/4');
INSERT INTO timeline (start_date) VALUES ('1992/03');
INSERT INTO timeline (start_date) VALUES ('1992/2');
INSERT INTO timeline (start_date) VALUES ('1992/01');
INSERT INTO timeline (start_date) VALUES ('1991/12');
INSERT INTO timeline (start_date) VALUES ('1991/11');
INSERT INTO timeline (start_date) VALUES ('1991/10');
INSERT INTO timeline (start_date) VALUES ('1991/09');
INSERT INTO timeline (start_date) VALUES ('1991/8');
INSERT INTO timeline (start_date) VALUES ('1991/07');
INSERT INTO timeline (start_date) VALUES ('1991/6');
INSERT INTO timeline (start_date) VALUES ('1991/05');
INSERT INTO timeline (start_date) VALUES ('1991/4');
INSERT INTO timeline (start_date) VALUES ('1991/03');
INSERT INTO timeline (start_date) VALUES ('1991/2');
INSERT INTO timeline (start_date) VALUES ('1991/01');
INSERT INTO timeline (start_date) VALUES ('1990/12');
INSERT INTO timeline (start_date) VALUES ('1990/11');
INSERT INTO timeline (start_date) VALUES ('1990/10');
INSERT INTO timeline (start_date) VALUES ('1990/09');
INSERT INTO timeline (start_date) VALUES ('1990/8');
INSERT INTO timeline (start_date) VALUES ('1990/07');
INSERT INTO timeline (start_date) VALUES ('1990/6');
INSERT INTO timeline (start_date) VALUES ('1990/05');
INSERT INTO timeline (start_date) VALUES ('1990/4');
INSERT INTO timeline (start_date) VALUES ('1990/03');
INSERT INTO timeline (start_date) VALUES ('1990/2');
INSERT INTO timeline (start_date) VALUES ('1990/01');
INSERT INTO timeline (start_date) VALUES ('1989/12');
INSERT INTO timeline (start_date) VALUES ('1989/11');
INSERT INTO timeline (start_date) VALUES ('1989/10');
INSERT INTO timeline (start_date) VALUES ('1989/09');
INSERT INTO timeline (start_date) VALUES ('1989/8');
INSERT INTO timeline (start_date) VALUES ('1989/07');
INSERT INTO timeline (start_date) VALUES ('1989/6');
INSERT INTO timeline (start_date) VALUES ('1989/05');
INSERT INTO timeline (start_date) VALUES ('1989/4');
INSERT INTO timeline (start_date) VALUES ('1989/03');
INSERT INTO timeline (start_date) VALUES ('1989/2');
INSERT INTO timeline (start_date) VALUES ('1989/01');
INSERT INTO timeline (start_date) VALUES ('1988/12');
INSERT INTO timeline (start_date) VALUES ('1988/11');
INSERT INTO timeline (start_date) VALUES ('1988/10');
INSERT INTO timeline (start_date) VALUES ('1988/09');
INSERT INTO timeline (start_date) VALUES ('1988/8');
INSERT INTO timeline (start_date) VALUES ('1988/07');
INSERT INTO timeline (start_date) VALUES ('1988/6');
INSERT INTO timeline (start_date) VALUES ('1988/05');
INSERT INTO timeline (start_date) VALUES ('1988/4');
INSERT INTO timeline (start_date) VALUES ('1988/03');
INSERT INTO timeline (start_date) VALUES ('1988/2');
INSERT INTO timeline (start_date) VALUES ('1988/01');
INSERT INTO timeline (start_date) VALUES ('1987/12');
INSERT INTO timeline (start_date) VALUES ('1987/11');
INSERT INTO timeline (start_date) VALUES ('1987/10');
INSERT INTO timeline (start_date) VALUES ('1987/09');
INSERT INTO timeline (start_date) VALUES ('1987/8');
INSERT INTO timeline (start_date) VALUES ('1987/07');
INSERT INTO timeline (start_date) VALUES ('1987/6');
INSERT INTO timeline (start_date) VALUES ('1987/05');
INSERT INTO timeline (start_date) VALUES ('1987/4');
INSERT INTO timeline (start_date) VALUES ('1987/03');
INSERT INTO timeline (start_date) VALUES ('1987/2');
INSERT INTO timeline (start_date) VALUES ('1987/01');
INSERT INTO timeline (start_date) VALUES ('1986/12');
INSERT INTO timeline (start_date) VALUES ('1986/11');
INSERT INTO timeline (start_date) VALUES ('1986/10');
INSERT INTO timeline (start_date) VALUES ('1986/09');
INSERT INTO timeline (start_date) VALUES ('1986/8');
INSERT INTO timeline (start_date) VALUES ('1986/07');
INSERT INTO timeline (start_date) VALUES ('1986/6');
INSERT INTO timeline (start_date) VALUES ('1986/05');
INSERT INTO timeline (start_date) VALUES ('1986/4');
INSERT INTO timeline (start_date) VALUES ('1986/03');
INSERT INTO timeline (start_date) VALUES ('1986/2');
INSERT INTO timeline (start_date) VALUES ('1986/01');
INSERT INTO timeline (start_date) VALUES ('1985/12');
INSERT INTO timeline (start_date) VALUES ('1985/11');
INSERT INTO timeline (start_date) VALUES ('1985/10');
INSERT INTO timeline (start_date) VALUES ('1985/09');
INSERT INTO timeline (start_date) VALUES ('1985/8');
INSERT INTO timeline (start_date) VALUES ('1985/07');
INSERT INTO timeline (start_date) VALUES ('1985/6');
INSERT INTO timeline (start_date) VALUES ('1985/05');
INSERT INTO timeline (start_date) VALUES ('1985/4');
INSERT INTO timeline (start_date) VALUES ('1985/03');
INSERT INTO timeline (start_date) VALUES ('1985/2');
INSERT INTO timeline (start_date) VALUES ('1985/01');
INSERT INTO timeline (start_date) VALUES ('1984/12');
INSERT INTO timeline (start_date) VALUES ('1984/11');
INSERT INTO timeline (start_date) VALUES ('1984/10');
INSERT INTO timeline (start_date) VALUES ('1984/09');
INSERT INTO timeline (start_date) VALUES ('1984/8');
INSERT INTO timeline (start_date) VALUES ('1984/07');
INSERT INTO timeline (start_date) VALUES ('1984/6');
INSERT INTO timeline (start_date) VALUES ('1984/05');
INSERT INTO timeline (start_date) VALUES ('1984/4');
INSERT INTO timeline (start_date) VALUES ('1984/03');
INSERT INTO timeline (start_date) VALUES ('1984/2');
INSERT INTO timeline (start_date) VALUES ('1984/01');
INSERT INTO timeline (start_date) VALUES ('1983/12');
INSERT INTO timeline (start_date) VALUES ('1983/11');
INSERT INTO timeline (start_date) VALUES ('1983/10');
INSERT INTO timeline (start_date) VALUES ('1983/09');
INSERT INTO timeline (start_date) VALUES ('1983/8');
INSERT INTO timeline (start_date) VALUES ('1983/07');
INSERT INTO timeline (start_date) VALUES ('1983/6');
INSERT INTO timeline (start_date) VALUES ('1983/05');
INSERT INTO timeline (start_date) VALUES ('1983/4');
INSERT INTO timeline (start_date) VALUES ('1983/03');
INSERT INTO timeline (start_date) VALUES ('1983/2');
INSERT INTO timeline (start_date) VALUES ('1983/01');
INSERT INTO timeline (start_date) VALUES ('1982/12');
INSERT INTO timeline (start_date) VALUES ('1982/11');
INSERT INTO timeline (start_date) VALUES ('1982/10');
INSERT INTO timeline (start_date) VALUES ('1982/09');
INSERT INTO timeline (start_date) VALUES ('1982/8');
INSERT INTO timeline (start_date) VALUES ('1982/07');
INSERT INTO timeline (start_date) VALUES ('1982/6');
INSERT INTO timeline (start_date) VALUES ('1982/05');
INSERT INTO timeline (start_date) VALUES ('1982/4');
INSERT INTO timeline (start_date) VALUES ('1982/03');
INSERT INTO timeline (start_date) VALUES ('1982/2');
INSERT INTO timeline (start_date) VALUES ('1982/01');
INSERT INTO timeline (start_date) VALUES ('1981/12');
INSERT INTO timeline (start_date) VALUES ('1981/11');
INSERT INTO timeline (start_date) VALUES ('1981/10');
INSERT INTO timeline (start_date) VALUES ('1981/09');
INSERT INTO timeline (start_date) VALUES ('1981/8');
INSERT INTO timeline (start_date) VALUES ('1981/07');
INSERT INTO timeline (start_date) VALUES ('1981/6');
INSERT INTO timeline (start_date) VALUES ('1981/05');
INSERT INTO timeline (start_date) VALUES ('1981/4');
INSERT INTO timeline (start_date) VALUES ('1981/03');
INSERT INTO timeline (start_date) VALUES ('1981/2');
INSERT INTO timeline (start_date) VALUES ('1981/01');
INSERT INTO timeline (start_date) VALUES ('1980/12');
INSERT INTO timeline (start_date) VALUES ('1980/11');
INSERT INTO timeline (start_date) VALUES ('1980/10');
INSERT INTO timeline (start_date) VALUES ('1980/09');
INSERT INTO timeline (start_date) VALUES ('1980/8');
INSERT INTO timeline (start_date) VALUES ('1980/07');
INSERT INTO timeline (start_date) VALUES ('1980/6');
INSERT INTO timeline (start_date) VALUES ('1980/05');
INSERT INTO timeline (start_date) VALUES ('1980/04');
INSERT INTO timeline (start_date) VALUES ('1980/3');
INSERT INTO timeline (start_date) VALUES ('1980/02');
INSERT INTO timeline (start_date) VALUES ('1980/01');
INSERT INTO timeline (start_date) VALUES ('1979/12');
INSERT INTO timeline (start_date) VALUES ('1979/11');
INSERT INTO timeline (start_date) VALUES ('1979/10');
INSERT INTO timeline (start_date) VALUES ('1979/9');
INSERT INTO timeline (start_date) VALUES ('1979/08');
INSERT INTO timeline (start_date) VALUES ('1979/07');
INSERT INTO timeline (start_date) VALUES ('1979/06');
INSERT INTO timeline (start_date) VALUES ('1979/5');
INSERT INTO timeline (start_date) VALUES ('1979/04');
INSERT INTO timeline (start_date) VALUES ('1979/03');

CREATE TABLE raw_content (cl0 TEXT, academic_resume_cv TEXT);

INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Undergraduate Studies');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'B.S., Computer Science, Johns Hopkins University, May 2001.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Teaching Experience');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'February 2009 to Present Data Management, Instructor for Talend Inc. and Independent');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Summer 2013   Entrepreneurship, Guest Lecture for United African University of Tanzania');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Spring 2010   Social Cause Games, Guest Lecture for U. of Southern California');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Sprint 2010   GMAT Prep, Instructor for RevolutionPrep');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Spring 2008   Sustainable Development, Guest Lecture for Chiang Mai University');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Spring 2007   Social Cause Games, Guest Lecture for Stanford Computer Science and RDVP');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Spring 1998   Computer Literacy, Instructor for Greenmount Community Foundation');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Publications');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Hickman, Darian “Innovations for Sustainable Development.” VillagetheGame.com. Mavgo LLC, May 2010. Web.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Research in Progress');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '“Farming Systems to Generate $400 of Food Using less than 5 hours of Labor.” Database in preparation for Village the Game 2.0. US edition.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '“TensorFlow Neural-Style Application” Case study in preparation for auto generating artwork for Village the Game');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Volunteer Experience');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Guest Lecturer. United African University of Tanzania. Taught 2 week business intensive on Entrepreneurship and Value Creation. July 2013');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Volunteer and Guest Instructor. Seeds of Hope. Upgraded IT systems and taught sessions on improving operations for 15 business units.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Volunteer. Blue Energy Group. Installed biosand filters and solar panels in Bluefields, Nicaragua.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Led 3-man team to build a customized PC for a blind friend with motion disabilities. Nov 2002 – May 2005');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Military Experience');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Completed Boot Camp and School of Infantry for US Marine Corps Reserves. Feb 2003 - Jul 2003.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Continued training as Rifleman in 4th Light Armored Reconnaissance Battalion USMCR, July 2003 – June 2005');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Work Experience');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Founder, Village the Game (www.villagethegame.com), May 2006 - Present');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Designed tech stack to scale on Google App Engine and make development rapid with Google Spreadsheets.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Recruited, managed 10 developers and 5 artists to build prototypes on multiple technology stacks.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Interviewed 7 social entrepreneurs on location in Kenya and India to learn how best to model their organizations.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Attended forums, gave presentations, and made over 200 contacts with business school, computer science students and alumni engaged in social ventures at Stanford, Caltech, UCLA, CMU, and USC.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Gave 5 interviews and received press from SF Chronicle, WorldChanging.com, NextBillion.net and many blogs and podcasts building a fan base for Village the Game.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Continuing to work on prototype development, recruiting investors, marketing partners, and advisors.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Talend Consultant, Mavgo, August 2011 - Present');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Installed, architected, validated, developed critical Talend features for managing data migration into Hortonworks datalake.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Migrated Informatica Jobs to Talend Platform at Catalina Marketing.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Developed Talend jobs for transforming multi-gigabyte data feeds daily.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Administered Talend Enterprise installations.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Integrated SQL solutions with Hadoop and NoSQL solutions like MongoDB.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Talend Architect Consultant, Home Depot and TCS, Sept 2014 - March 27, 2015');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Designed and developed Talend workflow for syncing LDAP changes to inhouse application. Used Talend Studio to generate daily complex xml messages delivered via Websphere MQ.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Designed and implemented Salesforce integration for augmenting call center capabilities. Learned Home Depot’s Continuous Integration infrastructure and ensured Talend jobs work accordingly.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Talend POC in prep for two year EAI project to augment inventory pickup and distribution. Validating read / write performance via Talend to Websphere and Active MQ’s in addition to throughput capabilities');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Solution Architect / Project Manager / Technical Lead, Luuruu, Feb 2014 - August 2014');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Designed a technology stack on Google App Engine, Google Sites, Google Spreadsheets, and Asana to help scale a translation company from under 5 translators to dozens of translators.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Gathered Client requirements and effectively delegated most of the Python development to overseas work while making updates to the code base myself where needed.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Talend Consultant, Google, October 2012 – October 2014');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Led team of 5 Googlers to install new versions of Talend Administration Center at two new data centers.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Talend Consultant, Independent March 2011 - Present');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Spring 2012 Taught online class on Talend ESB Platform over 4 week engagement.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Spring 2012 Project for EDIWatch: Trained staff onsite and advises on ways to automate more of fraud detection efforts in health care data.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Spring 2013 - Munters - trained class of 4 on Talend Studio 5.x via remote sessions.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Spring 2013 - Infogroup - trained class of 7 on Talend Enterprise 5.x via remote sessions.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Sales and Support Engineer, Talend Inc, (www.talend.com), Feb 2009 - Mar 2011');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Developed 100’s of custom demonstrations for Master Data Management, Data Integration, and Data Quality offerings.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Taught 30 training classes that comprised 2 - 20 students each.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Demonstrated Talend software 5 - 15 times each week since March 2009.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Provided support to close $1.2 million in new deals.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Programmer, Project Manager, Numedeon Inc. (www.numedeon.com), May 2008 – Nov 2008');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Led teams of 2-5 members to produce $68,000 worth of sponsored content inside www.whyville.net.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Managed 5 banner ad campaigns on Whyville that brought in $20,000 of supplemental revenue.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Managed weekly focus groups and surveys to determine the highest ROI upgrades to Whyville.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Managed 3-man team to build production estimates and price points for the 7 best in-world product placement campaigns and produced an ad kit to simplify the sale of these campaigns.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Conducted competitive analysis to determine best features to improve monthly uniques and revenue per user.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Software Engineer, Technology Management Associates, June 2004 – Apr 2005');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Built Java apps and PLSQL packages to transform and filter data from xml files, csv files into oracle data.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Upgraded and maintained JSP based web apps with geospatial data from Microstrategy Intelligence Server.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Software Engineer, Object Sciences Corporation, Sept. 2003 – June 2004.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Evaluated and deployed the best jabber instant messaging platforms B2B communication.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Demonstrated software for joint South Korean / US Army forces.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Software Engineer, ITT Industries, Advanced Engineering and Sciences, Jan. 2002 – Sept. 2003');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Trained 3 teammates in Java, Perl, and Redhat Linux Server Administration.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Additional Qualifications:');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'GMAT Scored 750 (98 percentile) on GMAT on August 11, 2007.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'GRE Scored 165 Verbal, 161 Quant, 4.5 Analytical Writing on April');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Honors, Scholarships, Fellowships');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '2009 Hendrickson Foundation Grant');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '1998 Ronald McDonald Foundation Grant');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '1997 Honor Society Scholarship');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Acting Resume');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Darian Hickman');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '5’ 7”; brown hair, brown eyes. | Whatsapp: +1 (424) 258-4850 | darian.hickman@gmail.com');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'FILM (Short / Student / Web Series)');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'When Harry Met a Ghost
Sushi Arcade
Roommates Unwanted');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Run Like Hell');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Mirror Mirror');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Naughty George');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'The Spy Who Annoyed Me');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Mind On Fire');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Drinking In LA');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'THEATRE');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'A Few Good Men');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Seven Deadly Sins');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'COMMERCIAL');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Conflicts available upon request.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'TRAINING');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Stand Up');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Scene Study & Monologues');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Movement');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Scene Study & Technique');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Scene Study');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Scene Study & Technique');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Audition Technique');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Voice');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Monologues');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Movement');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Filmcraft');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Comedy and Improv');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Audition Technique');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Scene Study');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Acting for Film');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Comedic Improv');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'University:  Johns Hopkins University - B.S. Computer Science');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Military: US Marine Corps - School of Infantry.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'SPECIAL SKILLS / TRAINING');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'Motorcycle, soccer, hand-to-hand combat, M16 rifle, squad automatic weapon, gas mask, rappelling; Marine Corps Martial Arts; volleyball, weight training, carpentry, rowing, yoga.');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'College Transcript');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', 'order');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '1');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '2');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '3');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '4');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '5');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '6');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '7');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '8');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '9');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '10');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '11');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '12');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '13');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '14');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '15');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '16');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '17');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '18');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '19');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '20');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '21');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '22');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '23');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '24');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '25');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '26');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '27');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '28');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '29');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '30');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '31');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '32');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '33');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '34');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '35');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '36');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '37');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '38');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '39');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '40');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '41');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '42');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '43');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '44');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '45');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '46');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '47');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '48');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '49');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '50');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');
INSERT INTO raw_content (cl0, academic_resume_cv) VALUES ('', '');

CREATE TABLE example_for_chatgpt (aboutme TEXT, acting_resume TEXT);

INSERT INTO example_for_chatgpt (aboutme, acting_resume) VALUES ('AboutMe', 'Darian Hickman');
INSERT INTO example_for_chatgpt (aboutme, acting_resume) VALUES ('AboutMe', '5’ 7”; brown hair, brown eyes. | Whatsapp: +1 (424) 258-4850 | darian.hickman@gmail.com');
INSERT INTO example_for_chatgpt (aboutme, acting_resume) VALUES ('', '');
INSERT INTO example_for_chatgpt (aboutme, acting_resume) VALUES ('Experience', 'FILM (Short / Student / Web Series)');
INSERT INTO example_for_chatgpt (aboutme, acting_resume) VALUES ('Experience', 'When Harry Met a Ghost
Sushi Arcade
Roommates Unwanted');
INSERT INTO example_for_chatgpt (aboutme, acting_resume) VALUES ('Experience', 'Run Like Hell');
